# docker-compose.yml
version: '3'

services:
  vault:
    image: influxdb:2.7
    container_name: influxdb
    restart: unless-stopped
    user: "${UID}:${GID}"
    volumes:
      - /opt/influxdb/data:/var/lib/influxdb2
      - /opt/influxdb/config:/etc/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${ADMIN_USER}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${ADMIN_PASS}
      DOCKER_INFLUXDB_INIT_ORG: ${ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${BUCKET}
    labels:
      - "traefik.http.routers.${TRAEFIK_REALM}.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.${TRAEFIK_REALM}.entrypoints=websecure"
      - "traefik.http.routers.${TRAEFIK_REALM}.tls.certresolver=letsencrypt"
      - "traefik.http.services.${TRAEFIK_REALM}.loadbalancer.server.port=8086"
      - "traefik.docker.network=web"

networks:
  default:
    external:
      name: web
